name: speexdsp

on: [push, pull_request]

jobs:
  rustfmt:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install stable
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true
        components: rustfmt
    - name: Run rustfmt
      uses: actions-rs/cargo@v1
      with:
        command: fmt
        args: -- --check --verbose

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install speexdsp
      run: |
        git clone https://github.com/xiph/speexdsp.git
        cd speexdsp
        ./autogen.sh
        ./configure --prefix=$HOME/speex_dir
        make
        make install
    - name: Run tests
      run: |
        export PKG_CONFIG_PATH=$HOME/speex_dir/lib/pkgconfig:$PKG_CONFIG_PATH
        export LD_LIBRARY_PATH=$HOME/speex_dir/lib:$LD_LIBRARY_PATH
        cargo test --all-features
        cargo test --no-default-features
